### ISSUE TITLE
Possible Privilege Escalation by using ProjectRoleTemplate

### ISSUE THREAD

**Issue by jiachengxu** [kubermatic/bulward#57]
`ProjectRoleTemplate` is used to manage project-specific role/rolebindings, and Organization Owner should have permission to manage `ProjectRoleTemplate`. 
Bulward controller manager service account should have `escalation` permission, because we should support managing arbitrary objects, for example, here is ProjectRoleTemplate to configure `myapp` api group:
```yaml
apiVersion: bulward.io/v1alpha1
kind: ProjectRoleTemplate
metadata:
  name: project-myapp-admin
  namespace: organization
spec:
  projectSelector: {}
  bindTo:
    - Everyone
  rules:
    - apiGroups:
        - myapp.example.io
      resources:
        - myapps
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
``` 
Because we cannot know all the resources in the projects in advance, controller manager should have `escalation` to create roles for granting permission for project members to access project-specific resources.

This can lead privilege escalation. Organization Owner cannot create role/rolebindings that escalates his/her permission directly, but the owner can do that by creating `ProjectRoleTemplate`, since bulward controller manager has `escalation` permission, so the role/rolebindings can be created.
